import type { NextPage } from "next";
import Head from "next/head";
import ChumbatarGenerator from "../../components/chumbatar-generator/ChumbatarGeneratorLanding";

const ChumbatarGeneratorPage: NextPage = () => {
  return (
    <div className="hero">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChumbatarGenerator />
    </div>
  );
};

export default ChumbatarGeneratorPage;
