import type { NextPage } from "next";
import Head from "next/head";
import ChumbatarGeneratorTemplate from "../templates/ChumbatarGeneratorTemplate";

const ChumbatarGenerator: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ChumbatarGeneratorTemplate />
    </div>
  );
};

export default ChumbatarGenerator;
