import type { NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import styled, { css } from "styled-components";
import Hero from "../components/home/Hero";
import Tools from "../components/home/Tools";
import { useTheme } from "../contexts/themeContext";
import { useWallet } from "../contexts/walletContext";
import { IColors } from "../interfaces/IColors";

declare global {
  interface Window {
    ethereum: any;
  }
}

const Home: NextPage = () => {
  const { colors, isDarkMode } = useTheme();

  const { connectWallet, current } = useWallet();

  useEffect(() => {
    if (connectWallet) {
      connectWallet();
    }

    console.log(current);
  }, [current]);

  return (
    <Container colors={colors} isDarkMode={isDarkMode}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero />
        <Tools />
      </main>
    </Container>
  );
};

const Container = styled.div<{ colors: IColors; isDarkMode: boolean }>`
  ${({ colors, isDarkMode }) => css`
    width: 100%;
    main {
      width: 100%;
      /* background-color: #021f1c; */
      background-color: ${isDarkMode ? colors.bg2 : colors.bg1};
    }
  `}
`;

export default Home;
